import button from './components/button.scss';
import input from './components/input.scss';
import loading from './components/loading.scss';
import modal from './components/modal.scss';
import pagination from './components/pagination.scss';
import progressCircle from './components/progress-circle.scss';
import progressLine from './components/progress-line.scss';
import rate from './components/rate.scss';
import rateItem from './components/rate-item.scss';
import select from './components/select.scss';
import splitLine from './components/split-line.scss';
import table from './components/table.scss';
import textarea from './components/textarea.scss';
import toast from './components/toast.scss';
import toggle from './components/toggle.scss';
import tooltip from './components/tooltip.scss';

const mixins = (style = {}, name = '') => () => Object.assign(style, { [name]: true });

export const buttonScss = mixins(button, 'pure-button');
export const inputScss = mixins(input, 'pure-input');
export const loadingScss = mixins(loading, 'pure-loading');
export const modalScss = mixins(modal, 'pure-modal');
export const paginationScss = mixins(pagination, 'pure-pagination');
export const progressCircleScss = mixins(progressCircle, 'pure-progress-circle');
export const progressLineScss = mixins(progressLine, 'pure-progress-line');
export const rateScss = mixins(rate, 'pure-rate');
export const rateItemScss = mixins(rateItem, 'pure-rate-item');
export const selectScss = mixins(select, 'pure-select');
export const splitLineScss = mixins(splitLine, 'pure-split-line');
export const tableScss = mixins(table, 'pure-table');
export const textareaScss = mixins(textarea, 'pure-textarea');
export const toastScss = mixins(toast, 'pure-toast');
export const toggleScss = mixins(toggle, 'pure-toggle');
export const tooltipScss = mixins(tooltip, 'pure-tooltip');
